Session6と7
yumemi-inc/k_uchiyama_ios_intern pull request #7
Opened 2022-12-22 08:46 UTC by Mayachiu

# Json文字列を扱う、Codable

### セッション6と7を同時にやりました

Xcode14.2を使用
（参考UIはiPhone 14 Pro）

## 課題リンク
https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Json.md
https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Codable.md

## 仕様
- APIをJSONバージョンに変更
- YumemiWeatherEntityを定義し、Codable対応
- 最高気温、最低気温について、画面に反映させた
- 軽微なUIの修正
- typeと以前のPRで頂いたアドバイスの修正

## 対応内容
[a522c45f40f52aec96e4a2680a9130e8edf37933] rebaseミスで残っていたtypeの修正
[72b9b468407c4e16127d446b7b647b17fbbbe14e] APIをJSONのものに修正し、レスポンスに関して、Codableにした
[d4c78ad57ec51350d569d38f370756e18f006a01] 受け取った温度について、画面に反映させた
[82d8756b6bf2defeb8c8dd60a70f56ef2f6d5776] コミットメッセージミスです。。。（push済み）温度ラベルのUIを修正しました
[14b0328360baa6671e066fb56abcdd3f582c2a8e] リクエストについてもCodableに対応しました
[0ea8b4315cc432aa6ecb1bd5f7d4d64effafff20] #6　で頂いたアドバイスで、エラーハンドリングの処理を変えました
[3441e828cafce3c2bd4de31dcd6097a442c98ed2] 余計なprintを消去しました
[ec46da7184c2ae823e3edfd098a78252b72b10e2] 強制アンラップがあり、危険な部分が残っていたので、修正しました

## UI差分

https://user-images.githubusercontent.com/83959618/209094429-556fcdfc-a198-406c-bff2-4d52f20e3aa7.mov

## チェック項目
- [ ] 呼び出しAPIをJson verに変更する
- [ ] 天気予報を画面に表示する（天気、最低気温、最高気温）

- [ ] Codableの仕組みを利用して、YumemiWeatherのAPIのパラメータを作成する
- [ ] Codableの仕組みを利用して、YumemiWeatherのAPIの結果を扱う

2022-12-22 14:52 UTC, ykws requested changes
前のセッションの課題内容であるエラーの扱いで不十分な部分があるため、ちょっとフィードバック内容が重いかもしれないですが、起こりうるエラーを整理して（API 側と App 側の境界も明確にし）適切に処理できるようになって欲しいと思いました。

2022-12-22 14:52 UTC, ykws commented on Yumemi-iOS-Training/Model/WeatherManager.swift
> +            var fetchedMaxTemperature = 0
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

ここで初期化している動機は何になりますか？

2022-12-22 14:52 UTC, ykws commented on Yumemi-iOS-Training/Model/YumemiWeatherEntity.swift
> +    enum CodingKeys: String, CodingKey {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

Web API と Swift の連携には CodingKeys を利用しないでシンプルに表現可能なのでぜひ試してみてください。

https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy/convertfromsnakecase

2022-12-22 14:52 UTC, ykws commented on Yumemi-iOS-Training/WeatherViewController.swift
> +        present(noWeatherAlert, animated: true, completion: nil)
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

completion には default value が設定されているので、 `nil` を渡す場合は省略可能です。

```suggestion
        present(noWeatherAlert, animated: true)
```

https://developer.apple.com/documentation/uikit/uiviewcontroller/1621380-present
https://docs.swift.org/swift-book/LanguageGuide/Functions.html

2022-12-22 14:52 UTC, ykws commented on Yumemi-iOS-Training/WeatherViewController.swift
> +    func updateWeather(_ fetchedWeatherCondition: String, _ fetchedMinTemperature: Int, _ fetchedMaxTemperature: Int) {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

メソッド名から各パラメータが何を扱うか余程明確ではない場合を除いて、引数名を省略することは避けた方が無難です。以下のドキュメントの省略する例も参考になると思います。

https://docs.swift.org/swift-book/LanguageGuide/Functions.html#ID166

2022-12-22 14:52 UTC, ykws commented on Yumemi-iOS-Training/Model/WeatherDelegate.swift
> +    func showNoWeatherResult(_ fetchedWeatherCondition: String)
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

show するかどうかは Delegate 側の責務ではないので異なる命名が相応しいです。
以下の指摘と同じ動機になります。

https://github.com/yumemi-inc/k_uchiyama_ios_intern/pull/5#discussion_r1054101391

2022-12-22 14:52 UTC, ykws commented on Yumemi-iOS-Training/WeatherViewController.swift
> +        let noWeatherAlert = UIAlertController(title: "天気を読み込めませんでした", message: nil, preferredStyle: .actionSheet)
![next-badge](https://img.shields.io/badge/review-next-blueviolet)

前の Session の課題内容なので別途で良いですが、以下の対応にも是非挑戦してみてください。

> エラーの内容に応じてメッセージを変更する
>
> https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Error.md

2022-12-22 14:52 UTC, ykws commented on Yumemi-iOS-Training/Model/APIClient.swift
> +        let requestedQueries = Request(area: "tokyo", date: "2020-04-01T12:00:00+09:00")
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

1件のリクエストなので Queries が複数になっているのが気になりました。

![next-badge](https://img.shields.io/badge/review-next-blueviolet)

Swift で日付を扱う Date にも是非挑戦してみてください。

https://developer.apple.com/documentation/foundation/date

2022-12-22 14:52 UTC, ykws commented on Yumemi-iOS-Training/Model/APIClient.swift
> +                completion(.failure(.invalidParameterError))
![must-badge](https://img.shields.io/badge/review-must-red.svg)

これは API が返すエラーなので、アプリ側のエラーに対して使ってしまうと、より上位の層でハンドリングできなくなってしまうので避けたいです。

https://yumemi-inc.github.io/ios-training/documentation/yumemiweather/yumemiweathererror/

2022-12-23 02:13 UTC, Mayachiu commented on Yumemi-iOS-Training/Model/WeatherManager.swift
> +            var fetchedMaxTemperature = 0
@ykws 
これはfetchedWeatherConditionがcase .successと case .failureのとき両方必要で、.failureのとき""を渡したい
という意図からvar fetchedWeatherCondition = ""としていました。それに習ってfetchedMinTemperatureとfetchedMaxTemperatureも同様の書き方をしていました。
しかし、.failureの場合にfetchedMinTemperatureとfetchedMaxTemperatureは渡す必要がないので、

```
var fetchedWeatherCondition = ""

switch result {
            case .success(let weatherResult):
                fetchedWeatherCondition = weatherResult.weatherCondition
                let fetchedMinTemperature = weatherResult.minTemperature
                let fetchedMaxTemperature = weatherResult.maxTemperature
                self.delegate?.updateWeather(fetchedWeatherCondition, fetchedMinTemperature, fetchedMaxTemperature)
            case .failure(let error):
                self.delegate?.showNoWeatherResult(fetchedWeatherCondition)
                print(error)
```

fetchedWeatherConditionに関してはそのままで、このようなのような形でいいと思いました。

2022-12-23 03:42 UTC, Mayachiu commented on Yumemi-iOS-Training/Model/APIClient.swift
> +                completion(.failure(.invalidParameterError))
```

enum FetchWeatherError:  LocalizedError {
    case failedConvertingDataToJson
    case failedConvertingJsonToData
    case failedEncoding
    case failedDecoding
　case APIError(YumemiWeatherError)

    var localizedDescription: String {
        switch self {
        case .failedConvertingDataToJson:
            return "データからJSONへの変換に失敗しました"
        case .failedConvertingJsonToData:
            return "JSONからデータへの変換に失敗しました"
        case .failedEncoding:
            return "エンコードに失敗しました"
        case .failedDecoding:
            return "デコードに失敗しました"
        case .APIError(let error):
            switch error {
            case .invalidParameterError:
                return "無効なパラメーターのエラーです"
            case .unknownError:
                return "不明なエラーが発生しました"
            }
        }
    }
}
```

このようなエラーを作って、データ→JSON、JSON→データ、エンコード、デコード、パラメーター、予期せぬエラーについて、ハンドリングすればいいと思いました

2022-12-23 09:52 UTC, Mayachiu commented
[b21ffdd](https://github.com/yumemi-inc/k_uchiyama_ios_intern/pull/7/commits/b21ffdd1269f03c6e5fb2dfcaf4dcaad7ee631f1)、[17c17d7](https://github.com/yumemi-inc/k_uchiyama_ios_intern/pull/7/commits/17c17d71324c663e73ca5f9336cc767c4f80d0ea)　エラーに関しての修正

[03b398d](https://github.com/yumemi-inc/k_uchiyama_ios_intern/pull/7/commits/03b398de91305e0f73c580f74de77c7572a61a2b)　Data型対応

[b9d9074](https://github.com/yumemi-inc/k_uchiyama_ios_intern/pull/7/commits/b9d9074c49e28f34664dd23e6be3f0cbdae0f0a1)　CodingKeys消去

[1e5c9e6](https://github.com/yumemi-inc/k_uchiyama_ios_intern/pull/7/commits/1e5c9e69824a40c37c2448fc1a33843c26759155)　delegateメソッドの命名修正

2022-12-26 01:07 UTC, Mayachiu commented
[252b94b](https://github.com/yumemi-inc/k_uchiyama_ios_intern/pull/7/commits/252b94bf3a6fd0117a7ef99c0d8c3ae80c53904c)
こちらでenum WeatherConditionを追加して、caseでdefaultを利用しなくても良い形にしました。また、画像などをAsset.swiftに切り出しました。

2022-12-26 03:18 UTC, yumemi-sishigaki commented on Yumemi-iOS-Training/Model/APIClient.swift
> +        decoder.keyDecodingStrategy = .convertFromSnakeCase
今回はAPI一つなのでいいのですが、複数のAPIがある場合ここで定義しているJSONEncoder等は同じものを使い回すと思うので、この部分だけ別のファンクションに切り出すのがいいかもですね。
(APIClientをstaticではなくクラスとして扱うなら、JSONEncoder等を生成するクラスを別に作ってDIする設計もいいかもですね。)

2022-12-26 03:28 UTC, yumemi-sishigaki approved these changes
(川島さんのレビューも含めて)全体的に良くなっていると思います！LGTM
ファンクションの処理を適切に切り出せたりすると取り回しも良くなって保守もしやすくなるので、気にしてみてください。
![LGTM](https://i.lgtm.fun/28ex.png)

2022-12-26 03:28 UTC, yumemi-sishigaki commented on Yumemi-iOS-Training/Model/YumemiWeatherEntity.swift
> +struct Response: Codable {
👍

2022-12-26 03:28 UTC, yumemi-sishigaki commented on Yumemi-iOS-Training/Model/APIClient.swift
> +        decoder.keyDecodingStrategy = .convertFromSnakeCase
今回はAPI一つなのでいいのですが、複数のAPIがある場合ここで定義しているJSONEncoder等は同じものを使い回すと思うので、この部分だけ別のファンクションに切り出すのがいいかもですね。
(APIClientをstaticではなくクラスとして扱うなら、JSONEncoder等を生成するクラスを別に作ってDIする設計もいいですね。)

2022-12-26 03:28 UTC, yumemi-sishigaki commented on Yumemi-iOS-Training/Model/YumemiWeatherEntity.swift
> +struct Request: Codable {
👍

2022-12-26 03:28 UTC, yumemi-sishigaki commented on Yumemi-iOS-Training/WeatherViewController.swift
> +            weatherImageView.image = Asset.sunnyImage.withRenderingMode(.alwaysTemplate)
今回のセッションの話ではないので、参考程度に。。
プロジェクト内の画像の扱いですが、ライブラリに抵抗がなければRswiftとか便利です。ゆめみでもよく使っていたと思います。
https://github.com/mac-cain13/R.swift

2022-12-26 03:30 UTC, merged

2022-12-26 13:21 UTC, ykws commented on Yumemi-iOS-Training/Model/APIClient.swift
> +                completion(.failure(.invalidParameterError))
@Mayachiu 良い感じだと思います！

LocalizedError に準拠するところも Swift らしくて 👍